###############################################################################
# Jekyll Configuration
highlighter: rouge
markdown: kramdown
permalink: /:title.html

###############################################################################
# Page Personal Details
url: https://gosia.huisman.pl
baseurl: /
author: Gosia Golanowska-Huisman
title: Gosia Golanowska-Huisman | Welcome to my homepage
description: Personal Landing Page
avatar: gosia.jpg

# Contacts
email: 

# Upon Request for Phone, Skype, Hangouts, etc.
urequest: 

# Social Usernames for Twitter, Github, Medium, Linkedin
username: 

# Research Outputs
google_scholar: 
orcid: 
